title: Truck Weight Calc
description: Essential utility app for truck drivers. Esimating axles, sliding tandems, state regulation and more.
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
